[package]
name = "poster"
version = "0.1.0"
edition = "2021"
readme = "README.md"
description = "MQTT library for Rust."
homepage = "https://github.com/Chylynsky/poster-rs"
repository = "https://github.com/Chylynsky/poster-rs"
categories = ["network-programming", "mqtt", "networking"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either = "1.8"
futures = "0.3"
bytes = "1.2"
derive_builder = "0.11"
